language: python
sudo: required

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

services:
  - elasticsearch

before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/1.7.3/elasticsearch-1.7.3.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.3.deb && sudo service elasticsearch restart

install:
  - "pip install webtest coverage nose-cov flake8 python-coveralls"
  - "pip install -e ."

before_script: "flake8"

script:
  - "curl -XGET localhost:9200"
  - "PYTHONHASHSEED='476010316' nosetests"

after_success:
  - coveralls
