language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

services:
  - elasticsearch

before_install:
  - "wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.4.deb && sudo dpkg -i --force-confnew elasticsearch-1.4.4.deb"

install:
  - "pip install webtest coverage nose-cov flake8 python-coveralls --use-mirrors"
  - "pip install -e . --use-mirrors"

before_script: "flake8"

script:  "nosetests"

after_success:
  - coveralls
